### PR TITLE
Move outlier analysis module to separate repository

### PR DESCRIPTION
**Pull request by gabefreedman**
This PR removes the 'outlier' module from enterprise_extensions. It will be placed in its own repository 'enterprise_outliers'. Dependency on Cython has been removed, and the setup.py file has been modified to reflect this.

Installation issues due to different gcc versions should now be resolved as the code causing this issue has been moved to 'enterprise_outliers'.

### CODE REVIEW

**Comment by Hazboun6** [comment]
I'm having a look through these changes now. @gabefreedman one thing that needs to be done is that _before_ merging your changes is that we need to version the current master so the timing pipeline is not required to change its installations.  And then we'll need to up the version number in your PR. I'll let you know when I know what that number should be!

**Review by Hazboun6 — CHANGES_REQUESTED** [review]
@gabefreedman this all looks very good! Thanks for the surgery you did. 

I've made a tagged version of the current code, so now we need to up the version number for your requested merge so that no one confuses them. If you look at this [PR](https://github.com/nanograv/enterprise_extensions/pull/124/files) you can see the handful of places you would change the version number, including the `README.md`.  I think `v2.2.0` would be a good jump. This is more than just a bug, but I'm not sure we need to change the major version number, unless @paulthebaker or someone else thinks we should jump up to 3. 

Can you make those changes please?

**Review by Hazboun6 — APPROVED** [review]

**Comment by gabefreedman** [comment]
@Hazboun6 Based on your suggestion from yesterday I've updated the version number to `v2.2.0` in the four necessary locations in my `outlier` branch. I see the changes have already been merged though. Is there anything you need me to do on my end to push the updated version number or is that all taken care of?

**Comment by Hazboun6** [comment]
@gabefreedman, Sorry I jumped the gun. I was just going to do it, but if you already have it done you could just submit another PR with those changes!

**Pull request merged**
