### PR TITLE
Fastlikelihood

### PR DESCRIPTION
**Pull request by AaronDJohnson**
Adds Michele's timing model for the faster likelihood calculation. This pull request includes the following:

1. Adds a tm_marg=False keyword to all models. When False, the calculation defaults to the usual likelihood calculation.
2. When tm_marg=True, the calculation adds the MarginalizedTimingModel instead of the usual TimingModel object.
3. Due to the way that things are working currently, this required a rearrangement so that the timing model is created in each model first.
4. Adds a CompareTimingModels class to model_utils that can compare speed and accuracy of the timing models by passing a string of the model to be used for comparison.
5. Assumes a new file in Enterprise called tm_marginal. In reality, this new timing model class could probably just exist in gp_signals.

This pull request is a draft until enterprise is updated with the final faster likelihood calculation.

### CODE REVIEW

**Comment by vallis** [comment]
Looks good Aaron, thanks! Two comments:

- In PR #288 on enterprise, MarginalizingTimingModel is indeed in gp_signals.
- I wonder if it is always meaningful to call each likelihood 10000 times. For a correlated GWB model, doing so tests the speed of the phi and Sigma inverses only; everything else is cached. There's more work that goes into making the Phi matrix, but that's the same for the two timing models. But in the presence of deterministic delays, or (gods forbid) should we be varying white noises, the tally would be different.

**Comment by AaronDJohnson** [comment]
Thanks @vallis !

>     * In PR #288 on enterprise, MarginalizingTimingModel is indeed in gp_signals.
I should have submitted another comment with the previous commit. The references to tm_marginal have been removed, and they have all been changed to gp_signals.

>     * I wonder if it is always meaningful to call each likelihood 10000 times...
This is a great point. I didn't consider other types of models. Is the issue that the caching would make it difficult to get accurate timing measurements? Would starting at a predetermined point (say the bottom of all priors) and perturbing the values before each likelihood calculation result in a more meaningful test?

**Comment by vallis** [comment]
Why not test at 10000 different parameter vectors? That would still exercise the TNT, etc. caching for GWBs, and the entire likelihood in other cases.

Also, since the testing in e_e is not very extensive, how does this PR change the default behavior of models, etc?  Does it actually need the new enterprise features to run, or only if the new features are requested?

**Comment by AaronDJohnson** [comment]
> Why not test at 10000 different parameter vectors? That would still exercise the TNT, etc. caching for GWBs, and the entire likelihood in other cases.

Okay! I'll implement this and update the PR.

> Also, since the testing in e_e is not very extensive, how does this PR change the default behavior of models, etc? Does it actually need the new enterprise features to run, or only if the new features are requested?

The default behavior of all models should be exactly as they were before this PR. Since the new timing model is now in gp_signals there are no new imports required to run each model. To be absolutely sure, I tested creating a model_2a from this commit on top of the conda version of enterprise-pulsar.

**Comment by Hazboun6** [comment]
@AaronDJohnson it looks the tests for this PR didn't start running. FYI, it's good to tag someone on these that is part of the dev team. Once the test run will this be ready to be merged? @stevertaylor and @svigeland is it okay to merge this or are we too far past the Sept 1 deadline?

**Comment by AaronDJohnson** [comment]
@Hazboun6 yes, everything has been ready for about a week on my side. Hopefully it's not too late to merge this, as it will make using the faster likelihood a bit easier through e_e.

**Pull request merged**
