### PR TITLE
adding new model_orfs module

### PR DESCRIPTION
**Pull request by stevertaylor**
First commit of new `model_orfs` module. Most functions are here. To be added are some functions for split-likelihood `bin_orf` and `legendre_orf` runs. Will require minor updates to `common_red_noise_block` too.

### CODE REVIEW

**Comment by stevertaylor** [comment]
Almost done with this. The last thing to be integrated is the option of a fixed amplitude parameter for the processes with zero autocorrelations but variable correlation parameters. Without a fixed amplitude parameter (or some other anchor) the ORF variation and amplitudes will just be completely degenerate.

**Comment by stevertaylor** [comment]
All code is now in place. Happy to merge myself, but if someone else like @josephjsimon or @Hazboun6 wants to take a look first then that's fine.

**Review by Hazboun6 — APPROVED** [review]
@stevertaylor This all looks wonderful! Lot of awesome code you've added in here!

**Comment by stevertaylor** [comment]
Merging now.

**Pull request merged**
