### PR TITLE
NANOGrav TWG WB noise setup

### PR DESCRIPTION
**Pull request by NihanPol**
This PR is to allow the NANOGrav TWG to directly call e_e.models.model_singlepsr_noise in future analyses, and thus allow for tighter (and more elegant) integration between timing_analysis package and the e_e.

This PR is required only for the WB analyses, where the TWG uses normal priors on DMEFAC and EFAC, and there is no easy way to do this with e_e right now.

To this end, the changes to the code are small and cosmetic: one flag, `ng_twg_setup = False` to enable this setup, and `wb_efac_sigma = 0.25` to set the sigma for the normal prior on the DM/EFAC parameters.

I have tested the flags and they setup the priors correctly. The code also works with the new implementation of DMEFAC/DMEQUAD in enterprise 3.3.1.

### CODE REVIEW

**Comment by NihanPol** [comment]
Unsure where the linting errors are coming from, but they seem to be from code that's not mine.

**Comment by AaronDJohnson** [comment]
@NihanPol see the change log for https://github.com/nanograv/enterprise_extensions/pull/188/commits/b91568558b16005a8a1549f88ed4e3e8815c89dc

**Comment by AaronDJohnson** [comment]
This has been fixed in several pull requests now, but it will continue to be a problem until one of them is accepted and merged.

**Comment by NihanPol** [comment]
The above commit updates the WidebandTimingModel API in all instances in models.py

**Comment by NihanPol** [comment]
@AaronDJohnson , @Hazboun6 , is there a way we can bypass the linting problem, or if you can tell me how to fix it on my end? @swiggumj and I would like to get this PR merged soon so that timing_analysis can be made public.

**Comment by AaronDJohnson** [comment]
@NihanPol, @swiggumj I made a comment up above which should help.

**Comment by AaronDJohnson** [comment]
@NihanPol I have merged a linting fix for the main branch. If you update this branch to that version, the checks should pass.

**Comment by NihanPol** [comment]
@AaronDJohnson Help! I'm not sure how to read and fix these lint issues.

**Comment by NihanPol** [comment]
Woo! Ready to merge, @AaronDJohnson ?

**Pull request merged**
