### PR TITLE
Fix sampler.py: check size of cov.npy matrix before loading

### PR DESCRIPTION
**Pull request by AaronDJohnson**
This adds a check to see if `resume=True` and also whether the size of the sample covariance matrix in cov.npy is correct before using that matrix.

### CODE REVIEW

**Comment by AaronDJohnson** [comment]
Fixes #174

**Comment by AaronDJohnson** [comment]
> Could you raise an error in the case where the existing `cov.npy` is the wrong size instead of making a default `cov` matrix? It seems that this would only happen if you are resuming in the wrong directory. In which case, you might not want to blindly continue on.

I have tried to be descriptive with the error that gets raised. What do you think?

**Comment by kdolum** [comment]
> I have tried to be descriptive with the error that gets raised. What do you think?

This looks good to me, thanks.

**Review by Hazboun6 — APPROVED** [review]
Thanks @AaronDJohnson ! These changes all look good to me. We should just get @paulthebaker to approve his review.

**Review by paulthebaker — APPROVED** [review]

**Pull request merged**
