### PR TITLE
KDE empirical distributions

### PR DESCRIPTION
**Pull request by meyers-academic**
Add option for using KDE empirical distributions. Update `extend` method to extend to edges of the prior in the same way as the histogram empirical distribution method. Also added tests similar to the ones that were there for the histogram empirical distribution. Happy to add more if people think they're necessary.

### CODE REVIEW

**Comment by meyers-academic** [comment]
@paulthebaker @AaronDJohnson This is the pull request for the KDE empirical distributions. I tried to make include error handling for if `scikit-learn` was not installed, and while it should work in the code, it actually doesn't work in the tests I wrote because I'm loading a pickled file that had it installed when I created the objects. Am I ok to just add this to the `requirements.txt` file? Or would you prefer that I find a different solution?

**Comment by meyers-academic** [comment]
@paulthebaker @AaronDJohnson I have come up with a somewhat hacky solution to the issue I was having, and I think this is ready for someone to look at. I have updated the requirements to insist on using an old version of `scikit-learn`, because it does not have support for python3.6 in its later versions. The only thing it is used for, though, works fine in that older version.

Otherwise, it would be good if someone could test this out before merging. I can share a notebook that runs it, or put an example in here if you'd like.

**Comment by meyers-academic** [comment]
* The pickles are empirical distribution pickles. They're used to test the `extend` method that extends the empirical distribution to the edge of the priors in cases where the empirical distribution is strongly peaked and they were not given the full prior range when they were created.
* Python 3.6 tries to install a newer version and the tests fail if I require `1.0.2` (which is the most recent production release, I think).

**Comment by meyers-academic** [comment]
That's a good point, though. If the test requires us to update the test every time we update the code then that's a bit useless. I can create dummy class instances needed to test the function on the fly and then run the extend function as a test. Then all that would need to be saved is some small number of samples used to create the dummy instances.

**Comment by vallis** [comment]
If the dummy class approach is not too much work, that would be good. "Golden copies" used for tests (if that's what these are) should be standard data files.

As for scikit-learn, let's pin it in requirements.txt but allow >= in setup.py. Doing so should allow users of higher Pythons to install newer versions if needed. Then we'll change the requirements once we drop Python 3.6.

**Comment by meyers-academic** [comment]
The dummy class approach should work fine. I have what I think is a working version

**Comment by Hazboun6** [comment]
@meyers-academic Are we ready to merge this?

**Comment by meyers-academic** [comment]
@Hazboun6, I think that everything I wanted, including updating tests to use a set of samples and creating empirical distributions on the fly is in there. However, there were some changes to the `extend_emp_dists`, for example, that it would be good if @AaronDJohnson could have a brief look at (see e.g. https://github.com/nanograv/enterprise_extensions/pull/159/commits/606aa8632ad43991a95ec138d909b3490b59ad5a, but probably best to just look at the final comparison with the main branch.)

**Pull request merged**
