### PR TITLE
Add outlier analysis package with HMC and Gibbs sampling

### PR DESCRIPTION
**Pull request by gabefreedman**
This PR adds an entire outlier package that contains modules for running a single pulsar outlier analysis using either Hamiltonian Monte Carlo or Gibbs sampling. The main setup.py file for enterprise_extensions is updated to included this new package, as well as commands necessary for cythonizing the C code accompanying the HMC sampler.

### CODE REVIEW

**Comment by Hazboun6** [comment]
@gabefreedman This looks like quite a lot of work! Thanks for putting this all together. I have yet to restart the CI testing with GitHub Actions, so no tests have been run with your software. Right now `e_e` is completely native Python. Have you installed this version of the software on the NG notebook server successfully? Or another non-local computer? I want to make sure that it doesn't make the rest of the package too difficult to install. 

Also, it looks like you haven't added any tests to the `/tests/` files. At the very least it would be good to write a few unit tests to make sure the various classes instantiate correctly and that methods can be called.

**Comment by stevertaylor** [comment]
Thanks @gabefreedman . Is the gibbs_outlier script just the one I added to the trello, or has it been modified?

**Comment by gabefreedman** [comment]
> Thanks @gabefreedman . Is the gibbs_outlier script just the one I added to the trello, or has it been modified?

The gibbs_outlier script is copied directly from the Trello board. The only change was renaming Gibbs --> OutlierGibbs in the class docstring example to match the name of the class.

**Comment by svigeland** [comment]
@gabefreedman, I got it installed on my machine, and it looks good except for a couple of minor things:
- `numdifftools` should be added to the `requirements.txt` file
- When I try importing all of the packages, some of them do not import and give the following error message:
> from enterprise_extensions.outlier import funnel
> Traceback (most recent call last):
>   File "<stdin>", line 1, in <module>
>   File "/Users/vigeland/PTAsoftware/gabe/enterprise_extensions/enterprise_extensions/outlier/funnel.py", line 19, in <module>
>     from .base import ptaLikelihood
>   File "/Users/vigeland/PTAsoftware/gabe/enterprise_extensions/enterprise_extensions/outlier/base.py", line 24, in <module>
>     from .jitterext import cython_Uj
> ModuleNotFoundError: No module named 'enterprise_extensions.outlier.jitterext'
Is this to be expected?

**Pull request merged**
